In [2]:
'''Task 1 — Generate and Inspect the Dataset Using NumPy random functions, 
create the following columns for 10 students: name (chosen randomly from a list of 5 names), 
age (random integers between 15 and 18), maths (random integers between 40 and 100), 
science (random integers between 40 and 100), and english (random integers between 40 and 100). 
Set np.random.seed(42) before generating any values. 
Print the shape of the marks array (only the three subject columns) and its dtype.'''
import numpy as np

num_students = 10
Names = ["Pavan","Varun","Krishna","Vamsi","Venu"]

np.random.seed(42)

name = np.random.choice(Names,size=num_students)
age = np.random.randint(15,19,size=num_students)
maths = np.random.randint(40,100,size=num_students)
science = np.random.randint(40,100,size=num_students)
english = np.random.randint(40,100,size=num_students)

marks = np.array([maths, science, english]).T
print(marks)

print("Shape:", marks.shape)
print("Dtype:", marks.dtype)

[[77 88 83]
 [41 66 94]
 [99 98 91]
 [60 81 96]
 [72 67 42]
 [51 99 76]
 [97 55 90]
 [61 54 46]
 [83 86 60]
 [64 90 48]]
Shape: (10, 3)
Dtype: int64


In [3]:
'''Task 2 — Reshape and Slice the Marks Array Take the marks array of shape (10, 3) 
and reshape it into shape (2, 5, 3). Print the reshaped array. Then, from the original (10, 3) marks array, 
slice and print the marks of the first five students for maths and science only (columns 0 and 1). 
In a comment, explain what the shape (2, 5, 3) represents in terms of the data.'''

marks_reshaped = marks.reshape(2,5,3)
print(f"Reshaped Marks :\n{marks_reshaped}")

student_marks = marks[0:5,:2]
print(f"first five student marks for maths and science :\n{student_marks}")

# Comment - (2, 5, 3) represents: 2 groups (or batches), each containing 5 students, and each student has 3 subject marks (maths, science, english).

Reshaped Marks :
[[[77 88 83]
  [41 66 94]
  [99 98 91]
  [60 81 96]
  [72 67 42]]

 [[51 99 76]
  [97 55 90]
  [61 54 46]
  [83 86 60]
  [64 90 48]]]
first five student marks for maths and science :
[[77 88]
 [41 66]
 [99 98]
 [60 81]
 [72 67]]


In [7]:
'''Task 3 — Save the Records to a File Write all 10 student records to a text file called student_records.txt, 
with each record on its own line in the format: Name | Age | Maths | Science | English. Use the with statement to open the file. 
Print a confirmation message after writing. Then open the file in read mode and print all lines to verify the output.'''

with open("student_records.txt","w") as file:
    file.write("Name | Age | Maths | Science | English\n")

    for i in range(num_students):
        file.write(f"{name[i]}, {age[i]}, {maths[i]}, {science[i]}, {english[i]}\n")
print("Data written successfully.")

with open("student_records.txt","r") as file:
    lines = file.readlines()
    for line in lines:
        print(line.strip())

Data written successfully.
Name | Age | Maths | Science | English
Vamsi, 18, 77, 88, 83
Venu, 18, 41, 66, 94
Krishna, 18, 99, 98, 91
Venu, 17, 60, 81, 96
Venu, 16, 72, 67, 42
Varun, 15, 51, 99, 76
Krishna, 16, 97, 55, 90
Krishna, 18, 61, 54, 46
Krishna, 18, 83, 86, 60
Venu, 16, 64, 90, 48
